version: '3.8'

services:
  # 1. The Backend API Engine
  api:
    build: .
    container_name: doc_api
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]

  # 2. The Frontend Streamlit Website
  ui:
    build: .
    container_name: doc_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    command: ["streamlit", "run", "app/ui.py", "--server.address", "0.0.0.0"]